//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STBLXMLEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STBLXMLEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified.
        /// </summary>
        internal static string ChineseSimplifiedLanguageName {
            get {
                return ResourceManager.GetString("ChineseSimplifiedLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional.
        /// </summary>
        internal static string ChineseTraditionalLanguageName {
            get {
                return ResourceManager.GetString("ChineseTraditionalLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designated key is already in use by another STBL entry, are you sure want to continue?.
        /// </summary>
        internal static string ConfimCollidingEntryKey {
            get {
                return ResourceManager.GetString("ConfimCollidingEntryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designated STBL file name is missing its language name formatting placeholder. This is necessary to differentiate STBL files and prevent them from sharing a file name. Are you sure you want to continue?
        ///
        ///Valid formatting placeholder are {0}, {0:Normal}, {0:Spaced}, {0:Underscored}, {0:Hyphenated}..
        /// </summary>
        internal static string ConfimSTBLNameMissingFormatting {
            get {
                return ResourceManager.GetString("ConfimSTBLNameMissingFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string CzechLanguageName {
            get {
                return ResourceManager.GetString("CzechLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        internal static string DanishLanguageName {
            get {
                return ResourceManager.GetString("DanishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string DutchLanguageName {
            get {
                return ResourceManager.GetString("DutchLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishLanguageName {
            get {
                return ResourceManager.GetString("EnglishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should we create the source info files needed for use with NeonOcean&apos;s package tool?.
        /// </summary>
        internal static string ExportCreateSourceInfoDialogText {
            get {
                return ResourceManager.GetString("ExportCreateSourceInfoDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Source Info Files?.
        /// </summary>
        internal static string ExportCreateSourceInfoDialogTitle {
            get {
                return ResourceManager.GetString("ExportCreateSourceInfoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        internal static string FinnishLanguageName {
            get {
                return ResourceManager.GetString("FinnishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string FrenchLanguageName {
            get {
                return ResourceManager.GetString("FrenchLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string GermanLanguageName {
            get {
                return ResourceManager.GetString("GermanLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        internal static string GreekLanguageName {
            get {
                return ResourceManager.GetString("GreekLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        internal static string HungarianLanguageName {
            get {
                return ResourceManager.GetString("HungarianLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No languages have been selected to for this file to be imported under..
        /// </summary>
        internal static string ImportNoLanguagesSelectedText {
            get {
                return ResourceManager.GetString("ImportNoLanguagesSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file or an invalid file has been selected..
        /// </summary>
        internal static string ImportNoOrInvalidFileText {
            get {
                return ResourceManager.GetString("ImportNoOrInvalidFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string ItalianLanguageName {
            get {
                return ResourceManager.GetString("ItalianLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string JapaneseLanguageName {
            get {
                return ResourceManager.GetString("JapaneseLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string KoreanLanguageName {
            get {
                return ResourceManager.GetString("KoreanLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No languages have been selected to merge..
        /// </summary>
        internal static string MergeWithNoLanguagesSelectedText {
            get {
                return ResourceManager.GetString("MergeWithNoLanguagesSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file or an invalid file has been selected..
        /// </summary>
        internal static string MergeWithNoOrInvalidFileText {
            get {
                return ResourceManager.GetString("MergeWithNoOrInvalidFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        internal static string NorwegianLanguageName {
            get {
                return ResourceManager.GetString("NorwegianLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the selected file..
        /// </summary>
        internal static string OpenFailureMessage {
            get {
                return ResourceManager.GetString("OpenFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string PolishLanguageName {
            get {
                return ResourceManager.GetString("PolishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese Brazil.
        /// </summary>
        internal static string PortugueseBrazilLanguageName {
            get {
                return ResourceManager.GetString("PortugueseBrazilLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese Portugal.
        /// </summary>
        internal static string PortuguesePortugalLanguageName {
            get {
                return ResourceManager.GetString("PortuguesePortugalLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string RussianLanguageName {
            get {
                return ResourceManager.GetString("RussianLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the loaded data..
        /// </summary>
        internal static string SaveFailureMessage {
            get {
                return ResourceManager.GetString("SaveFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0}.
        /// </summary>
        internal static string SelectorStatusBarItemsText {
            get {
                return ResourceManager.GetString("SelectorStatusBarItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: {0}.
        /// </summary>
        internal static string SelectorStatusBarSelectedText {
            get {
                return ResourceManager.GetString("SelectorStatusBarSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No languages have been selected to be sent off..
        /// </summary>
        internal static string SendToNoLanguagesSelectedText {
            get {
                return ResourceManager.GetString("SendToNoLanguagesSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file or an invalid file has been selected..
        /// </summary>
        internal static string SendToNoOrInvalidFileText {
            get {
                return ResourceManager.GetString("SendToNoOrInvalidFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish Mexico.
        /// </summary>
        internal static string SpanishMexicoLanguageName {
            get {
                return ResourceManager.GetString("SpanishMexicoLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish Spain.
        /// </summary>
        internal static string SpanishSpainLanguageName {
            get {
                return ResourceManager.GetString("SpanishSpainLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string SwedishLanguageName {
            get {
                return ResourceManager.GetString("SwedishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        internal static string ThaiLanguageName {
            get {
                return ResourceManager.GetString("ThaiLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string UnsavedDialogText {
            get {
                return ResourceManager.GetString("UnsavedDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string UnsavedDialogTitle {
            get {
                return ResourceManager.GetString("UnsavedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningMessageTitle {
            get {
                return ResourceManager.GetString("WarningMessageTitle", resourceCulture);
            }
        }
    }
}
